sudo: false
#blabla
services:
  - docker
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
matrix:
  include:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION='~> 3.0' BEAKER_set="debian-8-x86_64_docker" BEAKER_set="centos-7-x86_64_docker"
 

script: bundle exec rake spec SPEC_OPTS="--format documentation" && bundle exec rake beaker

notifications:
  email: false
