sudo: false
#blabla

language: ruby
cache: bundler
bundler_args: --without system_tests
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
matrix:
  include:
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION='~> 4.0' 
 

script: bundle exec rake spec SPEC_OPTS="--format documentation" 

notifications:
  email: false
