sudo: false
#blabla

language: ruby
cache: bundler
bundler_args: --without system_tests
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
matrix:
  include:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION='~> 3.7.4' BEAKER_set="ubuntu-12.10-x64"
 
deploy:
  provider: puppetforge
  user: "matsdp"
  password:
    secure: "HuC3a+/vBuwMc1gataSkWrixytr2iMk48RQn6Sqd/a5gzLNDHcfN95q9Aa4a+P5MZyaT6FjlXlJq7Yzrn5cIeFXCKHbrmuvIj73YdgH7lDrimPkD53DrA92YQ+oUbwpYi1o4OoNu+EKfvUPUmRslueE7M1of8MTSwOItaikJaS3vypR/afOyCMGSVU0xIJxUEkSxnQ2lzbuzELclCKJ34u2hr6jLt11aC9JA8AkxXlvNM/qwQyHec4pwevqzGHlhSm8BKdZxoYgMxGcHz7rlaA7BkMVVm7+gCINX2RqKbWTXTUgRGQ5yxfTKYE6dBKx+AYwrwUYF/T9p/xFzh7oGniutaQTj6qfGrmjZLKOkBr6azLeOq1RrSeS7jBs1PAVtCT/WUIDXKO2Yt4txqEYhlCwgYGyJv+v2XoK1Ro0xpLPqlXZEOMogz8uz//67vSByRMTwVRJ9KRsvpZyBH9GZ2XkFMC7woVdZOVFFquL8/DzVIX+o/R2Q2mYEKH97Daf5z2WcABY9062f8r/zJoMX5+XHVOrQP+3g2Klg8n/aTMHT+OYVo/hMKkDVYEfefeNPrgetVUYeO6VCrUCXMESw4CaYMmpbHAORZQ3DzZjnLKVaieed7KpruVoehayMPhCPsk98eHr9Ry2FORZGiPD8qCFSW8fUk+SHmXPd6ezEHI4="
  skip_cleanup: true
  
script: bundle exec rake test SPEC_OPTS="--format documentation" && bundle exec rake beaker SPEC_OPTS="--format documentation"


notifications:
  email: false
