HOSTS:
  debian-73-x64:
    platform: debian-7-amd64
    hypervisor : openstack
    flavor: m1.small
    image: debian-7-amd64-20141121
    user: debian
CONFIG:
  type: foss
  openstack_network: default
